[project]
name = "test-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "joblib>=1.6.0",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.52.4",
]
