name: CI/CD

# Trigger the workflow on push or pull request to the main branch
on:
  push: 
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # 1. download codes into github action runner 
    - name: Check out repository
      uses: actions/checkout@v4
    
    # 2. setup python 3.12
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    # 3. Install uv
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    # 4. Install dependecies
    - name: Install dependecies
      run: uv sync

    # 5. Train model
    - name: Train model
      run: uv run python -m src.train

    # 6. Run pytest
    - name: Run test
      run: uv run pytest

    # 7. Lint with Ruff (Assuming you added this!)
    - name: Lint with Ruff
      run: uv run ruff check 
    
      # -------------------------------------------------------------
    # CONTINUOUS DEPLOYMENT (CD) TO GITHUB CONTAINER REGISTRY
    # -------------------------------------------------------------
    
    # 8. Log into GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        # GITHUB_TOKEN is automatically provided by GitHub Actions
        password: ${{ secrets.GITHUB_TOKEN }}

    # 9. Build and Push the Docker Image
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        # Tags the image as ghcr.io/YOUR_GITHUB_USERNAME/REPO_NAME:latest
        tags: ghcr.io/${{ github.repository }}:latest

    # 7. build docker image
    # - name: Build docker image
    #   run: docker build -t churn-api:test .
