name: CI

# Trigger the workflow on push or pull request to the main branch
on:
  push: 
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # 1. download codes into github action runner 
    - name: Check out repository
      uses: actions/checkout@v4
    
    # 2. setup python 3.12
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    # 3. Install uv
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    # 4. Install dependecies
    - name: Install dependecies
      run: uv sync

    # 5. Train model
    - name: Train model
      run: uv run python -m src.train

    # 6. Run pytest
    - name: Run test
      run: uv run pytest

    # 7. build docker image
    - name: Build docker image
      run: docker build -t churn-api:test .
